Base_Node: 
  - Name: Main_Switch_Board
    Range_Name: X_Hand
    DeviceType: Switch_Board 
    Id: 101
    CH: Head_Flag_CH0
    IO_Mod: Main_CMD_IO_Mod_ETH_To_CAN
    PC_IP: *PC_IP
    IP: 192.168.3.101
    Port: 15100
    Up_Data_Speed: 1000
    Heart_Beat: true
    Save_Main_Config: true
    IO_Map:
      <<: *IO_Map_Default

    DeviceConfig:
      PrintMcuTaskStack: false
      Save_to_Flash: true
      Can_S:
       - Can_Instance: 1
         <<: *FD_Can_2M_2M
       - Can_Instance: 2
         <<: *FD_Can_2M_4M



# std::map<std::string, u32> IO_Mod_Map = {
# {"Main_CMD_IO_Mod_ETH_To_CAN", Main_CMD_IO_Mod_ETH_To_CAN},
# {"Main_CMD_IO_Mod_ETH_OR_CAN", Main_CMD_IO_Mod_ETH_OR_CAN},
# {"Main_CMD_IO_Mod_CAN_ONLY", Main_CMD_IO_Mod_CAN_ONLY}};


# enum Motor_CONTROL_MOD
# {
# Motor_Current_Control = 10,
# Motor_MIT_Control = 11,
# Motor_Pos_Control = 12,
# Motor_Force_Control = 13,
# Motor_Speed_Control = 14,

# Motor_MOD_END = 100,
# };





