config:
  TaiHu_Motor_Init_Config: &TaiHu_Init_Config
    TaiHu_Motor_Config: true
    TaiHu_Config_Save_Flash: false

  TaiHu_6070_Motor_config: &TaiHu_6070_Motor_config
    <<: *TaiHu_Init_Config 

    TaiHu_Reduction_Ratio: 101
    TaiHu_Pos_Offest: 0
    TaiHu_Forward_Vel: 7000
    TaiHu_Backward_vel: -7000
    TaiHu_Pos_Kp: 1200
    TaiHu_Pos_Kd: 500
    TaiHu_Vel_Kp: 600
    TaiHu_Vel_Ki: 300
    TaiHu_Cur_Kp: 3542
    TaiHu_Cur_Ki: 2510

  TaiHu_5060_Motor_config: &TaiHu_5060_Motor_config
    <<: *TaiHu_Init_Config 

    TaiHu_Reduction_Ratio: 101
    TaiHu_Pos_Offest: 0
    TaiHu_Forward_Vel: 7000
    TaiHu_Backward_vel: -7000
    TaiHu_Pos_Kp: 1200
    TaiHu_Pos_Kd: 500
    TaiHu_Vel_Kp: 600
    TaiHu_Vel_Ki: 300
    TaiHu_Cur_Kp: 3542
    TaiHu_Cur_Ki: 2510

  TaiHu_4052_Motor_config: &TaiHu_4052_Motor_config
    <<: *TaiHu_Init_Config 

    TaiHu_Reduction_Ratio: 101
    TaiHu_Pos_Offest: 0
    TaiHu_Forward_Vel: 7000
    TaiHu_Backward_vel: -7000
    TaiHu_Pos_Kp: 10000
    TaiHu_Pos_Kd: 2000
    TaiHu_Vel_Kp: 600
    TaiHu_Vel_Ki: 300
    TaiHu_Cur_Kp: 3542
    TaiHu_Cur_Ki: 2510

  TaiHu_3040_Motor_config: &TaiHu_3040_Motor_config
    <<: *TaiHu_Init_Config 

    TaiHu_Reduction_Ratio: 101
    TaiHu_Pos_Offest: 0
    TaiHu_Forward_Vel: 7000
    TaiHu_Backward_vel: -7000
    TaiHu_Pos_Kp: 10000
    TaiHu_Pos_Kd: 2000
    TaiHu_Vel_Kp: 600
    TaiHu_Vel_Ki: 300
    TaiHu_Cur_Kp: 3542
    TaiHu_Cur_Ki: 2510


