DriverVersion: 0.0.0
Log_Max_Size: 5
Name: Motor
PC_IP: &1 192.168.3.245
Broadcast_IP: 192.168.3.255
config:
  - "null": &2 false
  - "null": &3 false
  - Usr_Motor_Init_Config:
      Save_All_Config: &4 false
      Motor_EN_In_Init: &5 true
      Set_Zero_In_Init: &6 false
      Set_Config_In_Init: &7 false
      Set_Pid_Config_In_Init: &8 false
      Motor_Cal_In_Init: &9 false
  - Init_Config:
      Save_All_Config: &10 false
      Motor_EN_In_Init: &11 true
      Set_Zero_In_Init: &12 false
      Set_Config_In_Init: &13 false
      Set_Pid_Config_In_Init: &14 false
      Motor_Cal_In_Init: &15 false
  - MZ_10MM_Motor_default_config:
      Motor_Set_Zero_Offest: 0.0
      Motor_Mod: Motor_MIT_Control
      Motor_Heart_Beat: 0
      Motor_Pole_Pairs: 1
      Motor_AB_Mirror: false
      Motor_current_sample_offset: 10
      Dead_Time: 0
      V_IC_MU_FORCE: 200
      IC_MU_SPEED: 1
      V_rated: 300
      DI_I_MAX: 0.4
      I_Hardware_Max: 2
      Current_Amplifier_Gain: 10
      Motor_CMD_I_To_Force_K: 1.0
      Ceil_Temperature_Alarm_Th: 90
      Ceil_Temperature_Protect_Th: 100
      Gear_Ratio: 27.16875
      Gear_multiple: 50
      Electricity_D_P: 200000
      Electricity_D_I: 20000
      Electricity_D_OUT_MAX: 0.9
      Electricity_D_Integration_MAX: 0.9
      Electricity_Q_P: 200000
      Electricity_Q_I: 20000
      Electricity_Q_OUT_MAX: 0.9
      Electricity_Q_Integration_MAX: 0.9
  - MZ_13MM_Motor_default_config:
      Motor_Set_Zero_Offest: &16 0.0
      Motor_Mod: &17 Motor_MIT_Control
      Motor_Heart_Beat: &18 0
      Motor_Pole_Pairs: &19 1
      Motor_AB_Mirror: &20 false
      Motor_current_sample_offset: &21 10
      Dead_Time: &22 0
      V_IC_MU_FORCE: &23 200
      IC_MU_SPEED: &24 1
      V_rated: &25 300
      DI_I_MAX: &26 0.5
      I_Hardware_Max: &27 2
      Current_Amplifier_Gain: &28 10
      Motor_CMD_I_To_Force_K: &29 1.0
      Ceil_Temperature_Alarm_Th: &30 70
      Ceil_Temperature_Protect_Th: &31 90
      Gear_Ratio: &32 54
      Gear_multiple: &33 10
      Electricity_D_P: &34 200000
      Electricity_D_I: &35 20000
      Electricity_D_OUT_MAX: &36 0.90
      Electricity_D_Integration_MAX: &37 0.90
      Electricity_Q_P: &38 200000
      Electricity_Q_I: &39 20000
      Electricity_Q_OUT_MAX: &40 0.90
      Electricity_Q_Integration_MAX: &41 0.90
      Save_All_Config: *10
      Motor_EN_In_Init: *11
      Set_Zero_In_Init: *12
      Set_Config_In_Init: *13
      Set_Pid_Config_In_Init: *14
      Motor_Cal_In_Init: *15
  - cat_motor_device_config: &42
      Save_All_Config: *4
      Motor_EN_In_Init: *5
      Set_Zero_In_Init: *6
      Set_Config_In_Init: *7
      Set_Pid_Config_In_Init: *8
      Motor_Cal_In_Init: *9
      Motor_Set_Zero_Offest: *16
      Motor_Mod: *17
      Motor_Heart_Beat: *18
      Motor_Pole_Pairs: *19
      Motor_AB_Mirror: *20
      Motor_current_sample_offset: *21
      Dead_Time: *22
      V_IC_MU_FORCE: *23
      IC_MU_SPEED: *24
      V_rated: *25
      DI_I_MAX: *26
      I_Hardware_Max: *27
      Current_Amplifier_Gain: *28
      Motor_CMD_I_To_Force_K: *29
      Ceil_Temperature_Alarm_Th: *30
      Ceil_Temperature_Protect_Th: *31
      Gear_Ratio: *32
      Gear_multiple: *33
      Electricity_D_P: *34
      Electricity_D_I: *35
      Electricity_D_OUT_MAX: *36
      Electricity_D_Integration_MAX: *37
      Electricity_Q_P: *38
      Electricity_Q_I: *39
      Electricity_Q_OUT_MAX: *40
      Electricity_Q_Integration_MAX: *41
  - Motor_Config_Normal_0:
      DeviceType: &43 Motor_Device
      CH: &44 Head_Flag_Switch_CH1
      IO_Mod: &45 Main_CMD_IO_Mod_CAN_ONLY
  - Motor_Config_Normal_1:
      DeviceType: &46 Motor_Device
      CH: &47 Head_Flag_Switch_CH2
      IO_Mod: &48 Main_CMD_IO_Mod_CAN_ONLY
  - Led_Device_Config: &49
      Led_Start_En: true
      Led_Num: 20
      Tim_index: 1
      Tim_ch: 1
      All: false
      Led:
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
  - Led_Belt_Config:
      - &50
        Name: Led_GoGo
        DeviceType: Led_Device
        Id: 301
        CH: Head_Flag_Switch_CH1
        IO_Mod: Main_CMD_IO_Mod_CAN_ONLY
        Detect: false
        DeviceConfig: *49
  - MotorS_0:
      - &51
        Name: Motor_1
        Id: 1
        DeviceConfig: *42
        DeviceType: *43
        CH: *44
        IO_Mod: *45
      - &52
        Name: Motor_2
        Id: 1
        DeviceConfig: *42
        DeviceType: *43
        CH: *44
        IO_Mod: *45
      - &53
        Name: Motor_3
        Id: 1
        DeviceConfig: *42
        DeviceType: *43
        CH: *44
        IO_Mod: *45
      - &54
        Name: Motor_4
        Id: 1
        DeviceConfig: *42
        DeviceType: *43
        CH: *44
        IO_Mod: *45
      - &55
        Name: Motor_5
        Id: 1
        DeviceConfig: *42
        DeviceType: *43
        CH: *44
        IO_Mod: *45
      - &56
        Name: Motor_6
        Id: 1
        DeviceConfig: *42
        DeviceType: *43
        CH: *44
        IO_Mod: *45
      - &57
        Name: Motor_7
        Id: 1
        DeviceConfig: *42
        DeviceType: *43
        CH: *44
        IO_Mod: *45
      - &58
        Name: Motor_8
        Id: 1
        DeviceConfig: *42
        DeviceType: *43
        CH: *44
        IO_Mod: *45
      - &59
        Name: Motor_9
        Id: 1
        DeviceConfig: *42
        DeviceType: *43
        CH: *44
        IO_Mod: *45
      - &60
        Name: Motor_10
        Id: 1
        DeviceConfig: *42
        DeviceType: *43
        CH: *44
        IO_Mod: *45
      - &61
        Name: Motor_11
        Id: 1
        DeviceConfig: *42
        DeviceType: *43
        CH: *44
        IO_Mod: *45
      - &62
        Name: Motor_12
        Id: 1
        DeviceConfig: *42
        DeviceType: *43
        CH: *44
        IO_Mod: *45
      - &63
        Name: Motor_13
        Id: 1
        DeviceConfig: *42
        DeviceType: *43
        CH: *44
        IO_Mod: *45
      - &64
        Name: Motor_14
        Id: 1
        DeviceConfig: *42
        DeviceType: *43
        CH: *44
        IO_Mod: *45
  - MotorS_1:
      - &65
        Name: Motor_15
        Id: 1
        DeviceConfig: *42
        DeviceType: *46
        CH: *47
        IO_Mod: *48
      - &66
        Name: Motor_16
        Id: 1
        DeviceConfig: *42
        DeviceType: *46
        CH: *47
        IO_Mod: *48
      - &67
        Name: Motor_17
        Id: 1
        DeviceConfig: *42
        DeviceType: *46
        CH: *47
        IO_Mod: *48
      - &68
        Name: Motor_18
        Id: 1
        DeviceConfig: *42
        DeviceType: *46
        CH: *47
        IO_Mod: *48
      - &69
        Name: Motor_19
        Id: 1
        DeviceConfig: *42
        DeviceType: *46
        CH: *47
        IO_Mod: *48
      - &70
        Name: Motor_20
        Id: 1
        DeviceConfig: *42
        DeviceType: *46
        CH: *47
        IO_Mod: *48
      - &71
        Name: Motor_21
        Id: 1
        DeviceConfig: *42
        DeviceType: *46
        CH: *47
        IO_Mod: *48
      - &72
        Name: Motor_22
        Id: 1
        DeviceConfig: *42
        DeviceType: *46
        CH: *47
        IO_Mod: *48
      - &73
        Name: Motor_23
        Id: 1
        DeviceConfig: *42
        DeviceType: *46
        CH: *47
        IO_Mod: *48
      - &74
        Name: Motor_24
        Id: 1
        DeviceConfig: *42
        DeviceType: *46
        CH: *47
        IO_Mod: *48
      - &75
        Name: Motor_25
        Id: 1
        DeviceConfig: *42
        DeviceType: *46
        CH: *47
        IO_Mod: *48
      - &76
        Name: Motor_26
        Id: 1
        DeviceConfig: *42
        DeviceType: *46
        CH: *47
        IO_Mod: *48
      - &77
        Name: Motor_27
        Id: 1
        DeviceConfig: *42
        DeviceType: *46
        CH: *47
        IO_Mod: *48
      - &78
        Name: Motor_28
        Id: 1
        DeviceConfig: *42
        DeviceType: *46
        CH: *47
        IO_Mod: *48
  - Auto_Set_Id_DeviceS0:
      - &79
        Name: Auto_Set_Id_0
        DeviceType: Auto_Set_Id
        Detect: false
        Id: 1
        CH: Head_Flag_Switch_CH1
        IO_Mod: Main_CMD_IO_Mod_CAN_ONLY
        DeviceConfig:
          Run_Set: *2
          Start_Id: 11
          Save_Id: *3
          Time_Out_Ms: 1000
          DeviceList:
            - *51
            - *52
            - *53
            - *54
            - *55
            - *56
            - *57
            - *58
            - *59
            - *60
            - *61
            - *62
            - *63
            - *64
  - Auto_Set_Id_DeviceS1:
      - &80
        Name: Auto_Set_Id_1
        DeviceType: Auto_Set_Id
        Detect: false
        Id: 2
        CH: Head_Flag_Switch_CH2
        IO_Mod: Main_CMD_IO_Mod_CAN_ONLY
        DeviceConfig:
          Run_Set: *2
          Start_Id: 51
          Save_Id: *3
          Time_Out_Ms: 1000
          DeviceList:
            - *65
            - *66
            - *67
            - *68
            - *69
            - *70
            - *71
            - *72
            - *73
            - *74
            - *75
            - *76
            - *77
            - *78
Timer_Test_Config:
  - Timer_Instance: TIM3
    Timer_En: true
    Timer_Index: 1
    Prescaler: 239
    CounterMode: TIM_COUNTERMODE_UP
    Period: 999
    Tim_CHX:
      Timer_ChX: 1
      Timer_ChX_OutMode: PWM
      Timer_ChX_OCMode: TIM_OCMODE_PWM1
      Timer_ChX_Pulse: 200
      Timer_ChX_OCPolarity: TIM_OCPOLARITY_HIGH
      Timer_ChX_OCFastMode: TIM_OCFAST_DISABLE
      Timer_ChX_GPIO: GPIOC
      Timer_ChX_Pin: GPIO_PIN_6
      Timer_ChX_GPIO_Alternate: GPIO_AF2_TIM3
Timer_WS2812B_Config: &81
  - Timer_Instance: TIM17
    Timer_En: true
    Timer_Index: 1
    Prescaler: 0
    CounterMode: TIM_COUNTERMODE_UP
    Period: 311
    Tim_CHX:
      Timer_ChX: 1
      Timer_ChX_OutMode: DMA
      Timer_ChX_OCMode: TIM_OCMODE_PWM2
      Timer_ChX_Pulse: 0
      Timer_ChX_OCPolarity: TIM_OCPOLARITY_LOW
      Timer_ChX_OCFastMode: TIM_OCFAST_DISABLE
      Timer_ChX_GPIO: GPIOB
      Timer_ChX_Pin: GPIO_PIN_9
      Timer_ChX_GPIO_Alternate: GPIO_AF1_TIM17
      DMA_Config:
        Timer_Ch_DMA_Instance: DMA2_Stream0
        Timer_Ch_DMA_Request: DMA_REQUEST_TIM17_CH1
        Timer_Ch_DMA_Direction: DMA_MEMORY_TO_PERIPH
        Timer_Ch_DMA_PeriphInc: DMA_PINC_DISABLE
        Timer_Ch_DMA_MemInc: DMA_MINC_ENABLE
        Timer_Ch_DMA_PeriphDataAlignment: DMA_PDATAALIGN_HALFWORD
        Timer_Ch_DMA_MemDataAlignment: DMA_MDATAALIGN_HALFWORD
        Timer_Ch_DMA_Mode: DMA_NORMAL
        Timer_Ch_DMA_Priority: DMA_PRIORITY_MEDIUM
        Timer_Ch_DMA_FIFOMode: DMA_FIFOMODE_DISABLE
        Timer_Ch_DMA_Handle_index: TIM_DMA_ID_CC1
W_Bot_WS2812B_Config:
  - Timer_Instance: TIM2
    Timer_En: true
    Timer_Index: 1
    Prescaler: 0
    CounterMode: TIM_COUNTERMODE_UP
    Period: 311
    Tim_CHX:
      Timer_ChX: 1
      Timer_ChX_OutMode: DMA
      TIM_OCMODE_PWM2 Timer_ChX_OCMode: ~
      Timer_ChX_Pulse: 0
      Timer_ChX_OCPolarity: TIM_OCPOLARITY_LOW
      Timer_ChX_OCFastMode: TIM_OCFAST_DISABLE
      Timer_ChX_GPIO: GPIOA
      Timer_ChX_Pin: GPIO_PIN_0
      Timer_ChX_GPIO_Alternate: GPIO_AF1_TIM2
      DMA_Config:
        Timer_Ch_DMA_Instance: DMA1_Stream1
        Timer_Ch_DMA_Request: DMA_REQUEST_TIM2_CH1
        Timer_Ch_DMA_Direction: DMA_MEMORY_TO_PERIPH
        Timer_Ch_DMA_PeriphInc: DMA_PINC_DISABLE
        Timer_Ch_DMA_MemInc: DMA_MINC_ENABLE
        Timer_Ch_DMA_PeriphDataAlignment: DMA_PDATAALIGN_HALFWORD
        Timer_Ch_DMA_MemDataAlignment: DMA_MDATAALIGN_HALFWORD
        Timer_Ch_DMA_Mode: DMA_NORMAL
        Timer_Ch_DMA_Priority: DMA_PRIORITY_MEDIUM
        Timer_Ch_DMA_FIFOMode: DMA_FIFOMODE_DISABLE
        Timer_Ch_DMA_Handle_index: TIM_DMA_ID_CC1
Tim_2_WS2812B_Config:
  - Timer_Instance: TIM2
    Timer_En: true
    Timer_Index: 1
    Prescaler: 0
    CounterMode: TIM_COUNTERMODE_UP
    Period: 311
    Tim_CHX:
      Timer_ChX: 1
      Timer_ChX_OutMode: DMA
      TIM_OCMODE_PWM2 Timer_ChX_OCMode: ~
      Timer_ChX_Pulse: 0
      Timer_ChX_OCPolarity: TIM_OCPOLARITY_LOW
      Timer_ChX_OCFastMode: TIM_OCFAST_DISABLE
      Timer_ChX_GPIO: GPIOA
      Timer_ChX_Pin: GPIO_PIN_0
      Timer_ChX_GPIO_Alternate: GPIO_AF1_TIM2
      DMA_Config:
        Timer_Ch_DMA_Instance: DMA1_Stream1
        Timer_Ch_DMA_Request: DMA_REQUEST_TIM2_CH1
        Timer_Ch_DMA_Direction: DMA_MEMORY_TO_PERIPH
        Timer_Ch_DMA_PeriphInc: DMA_PINC_DISABLE
        Timer_Ch_DMA_MemInc: DMA_MINC_ENABLE
        Timer_Ch_DMA_PeriphDataAlignment: DMA_PDATAALIGN_HALFWORD
        Timer_Ch_DMA_MemDataAlignment: DMA_MDATAALIGN_HALFWORD
        Timer_Ch_DMA_Mode: DMA_NORMAL
        Timer_Ch_DMA_Priority: DMA_PRIORITY_MEDIUM
        Timer_Ch_DMA_FIFOMode: DMA_FIFOMODE_DISABLE
        Timer_Ch_DMA_Handle_index: TIM_DMA_ID_CC1
Tim_17_WS2812B_Config:
  Timer_Instance: TIM17
  Timer_En: true
  Timer_Index: 1
  Prescaler: 0
  CounterMode: TIM_COUNTERMODE_UP
  Period: 311
  Tim_CHX:
    Timer_ChX: 1
    Timer_ChX_OutMode: DMA
    Timer_ChX_OCMode: TIM_OCMODE_PWM2
    Timer_ChX_Pulse: 0
    Timer_ChX_OCPolarity: TIM_OCPOLARITY_LOW
    Timer_ChX_OCFastMode: TIM_OCFAST_DISABLE
    Timer_ChX_GPIO: GPIOB
    Timer_ChX_Pin: GPIO_PIN_9
    Timer_ChX_GPIO_Alternate: GPIO_AF1_TIM17
    DMA_Config:
      Timer_Ch_DMA_Instance: DMA2_Stream0
      Timer_Ch_DMA_Request: DMA_REQUEST_TIM17_CH1
      Timer_Ch_DMA_Direction: DMA_MEMORY_TO_PERIPH
      Timer_Ch_DMA_PeriphInc: DMA_PINC_DISABLE
      Timer_Ch_DMA_MemInc: DMA_MINC_ENABLE
      Timer_Ch_DMA_PeriphDataAlignment: DMA_PDATAALIGN_HALFWORD
      Timer_Ch_DMA_MemDataAlignment: DMA_MDATAALIGN_HALFWORD
      Timer_Ch_DMA_Mode: DMA_NORMAL
      Timer_Ch_DMA_Priority: DMA_PRIORITY_MEDIUM
      Timer_Ch_DMA_FIFOMode: DMA_FIFOMODE_DISABLE
      Timer_Ch_DMA_Handle_index: TIM_DMA_ID_CC1
Tim17_Head_Config:
  Timer_Instance: TIM17
  Timer_En: true
  Timer_Index: 1
  Prescaler: 0
  CounterMode: TIM_COUNTERMODE_UP
  Period: 311
Tim_Ch1_Config:
  Timer_ChX: 1
  Timer_ChX_OutMode: DMA
  Timer_ChX_OCMode: TIM_OCMODE_PWM2
  Timer_ChX_Pulse: 0
  Timer_ChX_OCPolarity: TIM_OCPOLARITY_LOW
  Timer_ChX_OCFastMode: TIM_OCFAST_DISABLE
  Timer_ChX_GPIO: GPIOB
  Timer_ChX_Pin: GPIO_PIN_9
  Timer_ChX_GPIO_Alternate: GPIO_AF1_TIM17
Tim_Ch_DMA1_Config:
  Timer_Ch_DMA_Instance: DMA2_Stream0
  Timer_Ch_DMA_Request: DMA_REQUEST_TIM17_CH1
  Timer_Ch_DMA_Direction: DMA_MEMORY_TO_PERIPH
  Timer_Ch_DMA_PeriphInc: DMA_PINC_DISABLE
  Timer_Ch_DMA_MemInc: DMA_MINC_ENABLE
  Timer_Ch_DMA_PeriphDataAlignment: DMA_PDATAALIGN_HALFWORD
  Timer_Ch_DMA_MemDataAlignment: DMA_MDATAALIGN_HALFWORD
  Timer_Ch_DMA_Mode: DMA_NORMAL
  Timer_Ch_DMA_Priority: DMA_PRIORITY_MEDIUM
  Timer_Ch_DMA_FIFOMode: DMA_FIFOMODE_DISABLE
  Timer_Ch_DMA_Handle_index: TIM_DMA_ID_CC1
Base_Node:
  - Name: Main_Switch_Board
    Range_Name: Motor
    DeviceType: Switch_Board
    Id: 101
    CH: Head_Flag_CH0
    IO_Mod: Main_CMD_IO_Mod_ETH_To_CAN
    PC_IP: *1
    IP: 192.168.3.101
    Port: 15100
    Up_Data_Speed: 10000
    Heart_Beat: true
    DeviceConfig:
      PrintMcuTaskStack: false
      Save_to_Flash: false
      Timer_S: *81
    child:
      - *50
      - *79
      - *51
      - *52
      - *53
      - *54
      - *55
      - *56
      - *57
      - *58
      - *59
      - *60
      - *61
      - *62
      - *63
      - *64
      - *80
      - *65
      - *66
      - *67
      - *68
      - *69
      - *70
      - *71
      - *72
      - *73
      - *74
      - *75
      - *76
      - *77
      - *78