DriverVersion: 0.0.1
Log_Max_Size: 5
Name: Motor
PC_IP: &1 192.168.3.245
Broadcast_IP: 192.168.3.255
config:
  - "null": &2 false
  - "null": &3 false
  - Usr_Motor_Init_Config:
      Save_All_Config: &4 false
      Motor_EN_In_Init: &5 true
      Set_Zero_In_Init: &6 false
      Set_Config_In_Init: &7 false
      Set_Pid_Config_In_Init: &8 false
      Motor_Cal_In_Init: &9 false
  - FD_Can_2M_4M:
      Can_EN: &10 true
      Can_FrameFormat: &11 FDCAN_FRAME_FD_BRS
      Can_Mode: &12 FDCAN_MODE_NORMAL
      Can_AutoRetransmission: &13 true
      Can_TransmitPause: &14 false
      Can_ProtocolException: &15 false
      Can_Nominal_Prescaler: &16 1
      Can_Nominal_SyncJumpWidth: &17 9
      Can_Nominal_TimeSeg1: &18 30
      Can_Nominal_TimeSeg2: &19 9
      Can_Data_Prescaler: &20 1
      Can_Data_SyncJumpWidth: &21 4
      Can_Data_TimeSeg1: &22 15
      Can_Data_TimeSeg2: &23 4
      Can_StdFiltersNbr: &24 4
      Can_ExtFiltersNbr: &25 4
      Can_RxFifo0ElmtsNbr: &26 32
      Can_RxFifo0ElmtSize: &27 FDCAN_DATA_BYTES_64
      Can_RxFifo1ElmtsNbr: &28 0
      Can_RxFifo1ElmtSize: &29 FDCAN_DATA_BYTES_64
      Can_RxBuffersNbr: &30 0
      Can_RxBufferSize: &31 FDCAN_DATA_BYTES_64
      Can_TxEventsNbr: &32 0
      Can_TxBuffersNbr: &33 0
      Can_TxFifoQueueElmtsNbr: &34 16
      Can_TxFifoQueueMode: &35 FDCAN_TX_FIFO_OPERATION
      Can_TxElmtSize: &36 FDCAN_DATA_BYTES_64
      Can_Set_Complete: &37 true
  - FD_Can_2M_2M:
      Can_EN: true
      Can_FrameFormat: FDCAN_FRAME_FD_BRS
      Can_Mode: FDCAN_MODE_NORMAL
      Can_AutoRetransmission: true
      Can_TransmitPause: false
      Can_ProtocolException: false
      Can_Nominal_Prescaler: 1
      Can_Nominal_SyncJumpWidth: 9
      Can_Nominal_TimeSeg1: 30
      Can_Nominal_TimeSeg2: 9
      Can_Data_Prescaler: 1
      Can_Data_SyncJumpWidth: 9
      Can_Data_TimeSeg1: 30
      Can_Data_TimeSeg2: 9
      Can_StdFiltersNbr: 4
      Can_ExtFiltersNbr: 4
      Can_RxFifo0ElmtsNbr: 32
      Can_RxFifo0ElmtSize: FDCAN_DATA_BYTES_64
      Can_RxFifo1ElmtsNbr: 0
      Can_RxFifo1ElmtSize: FDCAN_DATA_BYTES_64
      Can_RxBuffersNbr: 0
      Can_RxBufferSize: FDCAN_DATA_BYTES_64
      Can_TxEventsNbr: 0
      Can_TxBuffersNbr: 0
      Can_TxFifoQueueElmtsNbr: 16
      Can_TxFifoQueueMode: FDCAN_TX_FIFO_OPERATION
      Can_TxElmtSize: FDCAN_DATA_BYTES_64
      Can_Set_Complete: true
  - FD_Can_1M_5M:
      Can_EN: true
      Can_FrameFormat: FDCAN_FRAME_FD_BRS
      Can_Mode: FDCAN_MODE_NORMAL
      Can_AutoRetransmission: true
      Can_TransmitPause: false
      Can_ProtocolException: false
      Can_Nominal_Prescaler: 1
      Can_Nominal_SyncJumpWidth: 16
      Can_Nominal_TimeSeg1: 63
      Can_Nominal_TimeSeg2: 16
      Can_Data_Prescaler: 1
      Can_Data_SyncJumpWidth: 7
      Can_Data_TimeSeg1: 8
      Can_Data_TimeSeg2: 7
      Can_StdFiltersNbr: 4
      Can_ExtFiltersNbr: 4
      Can_RxFifo0ElmtsNbr: 32
      Can_RxFifo0ElmtSize: FDCAN_DATA_BYTES_64
      Can_RxFifo1ElmtsNbr: 0
      Can_RxFifo1ElmtSize: FDCAN_DATA_BYTES_64
      Can_RxBuffersNbr: 0
      Can_RxBufferSize: FDCAN_DATA_BYTES_64
      Can_TxEventsNbr: 0
      Can_TxBuffersNbr: 0
      Can_TxFifoQueueElmtsNbr: 16
      Can_TxFifoQueueMode: FDCAN_TX_FIFO_OPERATION
      Can_TxElmtSize: FDCAN_DATA_BYTES_64
      Can_Set_Complete: true
  - Classic_Can_1M:
      Can_EN: true
      Can_FrameFormat: FDCAN_FRAME_CLASSIC
      Can_Mode: FDCAN_MODE_NORMAL
      Can_AutoRetransmission: true
      Can_TransmitPause: false
      Can_ProtocolException: false
      Can_Nominal_Prescaler: 2
      Can_Nominal_SyncJumpWidth: 9
      Can_Nominal_TimeSeg1: 30
      Can_Nominal_TimeSeg2: 9
      Can_Data_Prescaler: 1
      Can_Data_SyncJumpWidth: 4
      Can_Data_TimeSeg1: 15
      Can_Data_TimeSeg2: 4
      Can_StdFiltersNbr: 4
      Can_ExtFiltersNbr: 4
      Can_RxFifo0ElmtsNbr: 32
      Can_RxFifo0ElmtSize: FDCAN_DATA_BYTES_64
      Can_RxFifo1ElmtsNbr: 0
      Can_RxFifo1ElmtSize: FDCAN_DATA_BYTES_64
      Can_RxBuffersNbr: 0
      Can_RxBufferSize: FDCAN_DATA_BYTES_64
      Can_TxEventsNbr: 0
      Can_TxBuffersNbr: 0
      Can_TxFifoQueueElmtsNbr: 16
      Can_TxFifoQueueMode: FDCAN_TX_FIFO_OPERATION
      Can_TxElmtSize: FDCAN_DATA_BYTES_64
      Can_Set_Complete: true
  - Init_Config:
      Save_All_Config: &38 false
      Motor_EN_In_Init: &39 true
      Set_Zero_In_Init: &40 false
      Set_Config_In_Init: &41 false
      Set_Pid_Config_In_Init: &42 false
      Motor_Cal_In_Init: &43 false
  - MZ_10MM_Motor_default_config:
      Motor_Set_Zero_Offest: 0.0
      Motor_Mod: Motor_MIT_Control
      Motor_Heart_Beat: 0
      Motor_Pole_Pairs: 1
      Motor_AB_Mirror: false
      Motor_current_sample_offset: 10
      MD_K: 10
      Dead_Time: 1
      V_IC_MU_FORCE: 200
      IC_MU_SPEED: 1
      V_rated: 700
      DI_I_MAX: 2.0
      I_Hardware_Max: 2
      Current_Amplifier_Gain: 15
      Motor_CMD_I_To_Force_K: 1.0
      Ceil_Temperature_Alarm_Th: 90
      Ceil_Temperature_Protect_Th: 100
      NTC_Bx: 3950
      Gear_Ratio: 27.16875
      Gear_multiple: 50
      Electricity_D_P: 200000
      Electricity_D_I: 20000
      Electricity_D_OUT_MAX: 0.9
      Electricity_D_Integration_MAX: 0.9
      Electricity_Q_P: 200000
      Electricity_Q_I: 20000
      Electricity_Q_OUT_MAX: 0.9
      Electricity_Q_Integration_MAX: 0.9
  - MZ_13MM_Motor_default_config:
      Motor_Set_Zero_Offest: &44 0.0
      Motor_Mod: &45 Motor_MIT_Control
      Motor_Heart_Beat: &46 0
      Motor_Pole_Pairs: &47 1
      Motor_AB_Mirror: &48 false
      Motor_current_sample_offset: &49 10
      MD_K: &50 10
      Dead_Time: &51 1
      V_IC_MU_FORCE: &52 200
      IC_MU_SPEED: &53 1
      V_rated: &54 500
      DI_I_MAX: &55 0.5
      I_Hardware_Max: &56 2
      Current_Amplifier_Gain: &57 15
      Motor_CMD_I_To_Force_K: &58 1.0
      Ceil_Temperature_Alarm_Th: &59 70
      Ceil_Temperature_Protect_Th: &60 90
      NTC_Bx: &61 3950
      Gear_Ratio: &62 54
      Gear_multiple: &63 10
      Electricity_D_P: &64 200000
      Electricity_D_I: &65 20000
      Electricity_D_OUT_MAX: &66 0.90
      Electricity_D_Integration_MAX: &67 0.90
      Electricity_Q_P: &68 200000
      Electricity_Q_I: &69 20000
      Electricity_Q_OUT_MAX: &70 0.90
      Electricity_Q_Integration_MAX: &71 0.90
      Save_All_Config: *38
      Motor_EN_In_Init: *39
      Set_Zero_In_Init: *40
      Set_Config_In_Init: *41
      Set_Pid_Config_In_Init: *42
      Motor_Cal_In_Init: *43
  - cat_motor_device_config: &72
      Save_All_Config: *4
      Motor_EN_In_Init: *5
      Set_Zero_In_Init: *6
      Set_Config_In_Init: *7
      Set_Pid_Config_In_Init: *8
      Motor_Cal_In_Init: *9
      Motor_Set_Zero_Offest: *44
      Motor_Mod: *45
      Motor_Heart_Beat: *46
      Motor_Pole_Pairs: *47
      Motor_AB_Mirror: *48
      Motor_current_sample_offset: *49
      MD_K: *50
      Dead_Time: *51
      V_IC_MU_FORCE: *52
      IC_MU_SPEED: *53
      V_rated: *54
      DI_I_MAX: *55
      I_Hardware_Max: *56
      Current_Amplifier_Gain: *57
      Motor_CMD_I_To_Force_K: *58
      Ceil_Temperature_Alarm_Th: *59
      Ceil_Temperature_Protect_Th: *60
      NTC_Bx: *61
      Gear_Ratio: *62
      Gear_multiple: *63
      Electricity_D_P: *64
      Electricity_D_I: *65
      Electricity_D_OUT_MAX: *66
      Electricity_D_Integration_MAX: *67
      Electricity_Q_P: *68
      Electricity_Q_I: *69
      Electricity_Q_OUT_MAX: *70
      Electricity_Q_Integration_MAX: *71
  - Motor_Config_Normal_0:
      DeviceType: &73 Motor_Device
      CH: &74 Head_Flag_Switch_CH1
      IO_Mod: &75 Main_CMD_IO_Mod_CAN_ONLY
  - Motor_Config_Normal_1:
      DeviceType: &76 Motor_Device
      CH: &77 Head_Flag_Switch_CH2
      IO_Mod: &78 Main_CMD_IO_Mod_CAN_ONLY
  - Led_Device_Config: &79
      Led_Start_En: true
      Led_Num: 20
      Tim_index: 1
      Tim_ch: 1
      All: false
      Led:
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
        - [0, 0, 125]
  - Led_Belt_Config:
      - &80
        Name: Led_GoGo
        DeviceType: Led_Device
        Id: 301
        CH: Head_Flag_Switch_CH1
        IO_Mod: Main_CMD_IO_Mod_CAN_ONLY
        Detect: false
        DeviceConfig: *79
  - MotorS_0:
      - &81
        Name: Motor_1
        Id: 1
        DeviceConfig: *72
        DeviceType: *73
        CH: *74
        IO_Mod: *75
      - &82
        Name: Motor_2
        Id: 1
        DeviceConfig: *72
        DeviceType: *73
        CH: *74
        IO_Mod: *75
      - &83
        Name: Motor_3
        Id: 1
        DeviceConfig: *72
        DeviceType: *73
        CH: *74
        IO_Mod: *75
      - &84
        Name: Motor_4
        Id: 1
        DeviceConfig: *72
        DeviceType: *73
        CH: *74
        IO_Mod: *75
      - &85
        Name: Motor_5
        Id: 1
        DeviceConfig: *72
        DeviceType: *73
        CH: *74
        IO_Mod: *75
      - &86
        Name: Motor_6
        Id: 1
        DeviceConfig: *72
        DeviceType: *73
        CH: *74
        IO_Mod: *75
      - &87
        Name: Motor_7
        Id: 1
        DeviceConfig: *72
        DeviceType: *73
        CH: *74
        IO_Mod: *75
      - &88
        Name: Motor_8
        Id: 1
        DeviceConfig: *72
        DeviceType: *73
        CH: *74
        IO_Mod: *75
      - &89
        Name: Motor_9
        Id: 1
        DeviceConfig: *72
        DeviceType: *73
        CH: *74
        IO_Mod: *75
      - &90
        Name: Motor_10
        Id: 1
        DeviceConfig: *72
        DeviceType: *73
        CH: *74
        IO_Mod: *75
      - &91
        Name: Motor_11
        Id: 1
        DeviceConfig: *72
        DeviceType: *73
        CH: *74
        IO_Mod: *75
      - &92
        Name: Motor_12
        Id: 1
        DeviceConfig: *72
        DeviceType: *73
        CH: *74
        IO_Mod: *75
      - &93
        Name: Motor_13
        Id: 1
        DeviceConfig: *72
        DeviceType: *73
        CH: *74
        IO_Mod: *75
      - &94
        Name: Motor_14
        Id: 1
        DeviceConfig: *72
        DeviceType: *73
        CH: *74
        IO_Mod: *75
  - MotorS_1:
      - &95
        Name: Motor_15
        Id: 1
        DeviceConfig: *72
        DeviceType: *76
        CH: *77
        IO_Mod: *78
      - &96
        Name: Motor_16
        Id: 1
        DeviceConfig: *72
        DeviceType: *76
        CH: *77
        IO_Mod: *78
      - &97
        Name: Motor_17
        Id: 1
        DeviceConfig: *72
        DeviceType: *76
        CH: *77
        IO_Mod: *78
      - &98
        Name: Motor_18
        Id: 1
        DeviceConfig: *72
        DeviceType: *76
        CH: *77
        IO_Mod: *78
      - &99
        Name: Motor_19
        Id: 1
        DeviceConfig: *72
        DeviceType: *76
        CH: *77
        IO_Mod: *78
      - &100
        Name: Motor_20
        Id: 1
        DeviceConfig: *72
        DeviceType: *76
        CH: *77
        IO_Mod: *78
      - &101
        Name: Motor_21
        Id: 1
        DeviceConfig: *72
        DeviceType: *76
        CH: *77
        IO_Mod: *78
      - &102
        Name: Motor_22
        Id: 1
        DeviceConfig: *72
        DeviceType: *76
        CH: *77
        IO_Mod: *78
      - &103
        Name: Motor_23
        Id: 1
        DeviceConfig: *72
        DeviceType: *76
        CH: *77
        IO_Mod: *78
      - &104
        Name: Motor_24
        Id: 1
        DeviceConfig: *72
        DeviceType: *76
        CH: *77
        IO_Mod: *78
      - &105
        Name: Motor_25
        Id: 1
        DeviceConfig: *72
        DeviceType: *76
        CH: *77
        IO_Mod: *78
      - &106
        Name: Motor_26
        Id: 1
        DeviceConfig: *72
        DeviceType: *76
        CH: *77
        IO_Mod: *78
      - &107
        Name: Motor_27
        Id: 1
        DeviceConfig: *72
        DeviceType: *76
        CH: *77
        IO_Mod: *78
      - &108
        Name: Motor_28
        Id: 1
        DeviceConfig: *72
        DeviceType: *76
        CH: *77
        IO_Mod: *78
  - Auto_Set_Id_DeviceS0:
      - &109
        Name: Auto_Set_Id_0
        DeviceType: Auto_Set_Id
        Detect: false
        Id: 1
        CH: Head_Flag_Switch_CH1
        IO_Mod: Main_CMD_IO_Mod_CAN_ONLY
        DeviceConfig:
          Run_Set: *2
          Start_Id: 11
          Save_Id: *3
          Time_Out_Ms: 1000
          DeviceList:
            - *81
            - *82
            - *83
            - *84
            - *85
            - *86
            - *87
            - *88
            - *89
            - *90
            - *91
            - *92
            - *93
            - *94
  - Auto_Set_Id_DeviceS1:
      - &110
        Name: Auto_Set_Id_1
        DeviceType: Auto_Set_Id
        Detect: false
        Id: 2
        CH: Head_Flag_Switch_CH2
        IO_Mod: Main_CMD_IO_Mod_CAN_ONLY
        DeviceConfig:
          Run_Set: *2
          Start_Id: 51
          Save_Id: *3
          Time_Out_Ms: 1000
          DeviceList:
            - *95
            - *96
            - *97
            - *98
            - *99
            - *100
            - *101
            - *102
            - *103
            - *104
            - *105
            - *106
            - *107
            - *108
Timer_WS2812B_Config:
  - Timer_Instance: TIM17
    Timer_En: true
    Timer_Index: 1
    Prescaler: 0
    CounterMode: TIM_COUNTERMODE_UP
    Period: 311
    Tim_CHX:
      Timer_ChX: 1
      Timer_ChX_OutMode: DMA
      Timer_ChX_OCMode: TIM_OCMODE_PWM2
      Timer_ChX_Pulse: 0
      Timer_ChX_OCPolarity: TIM_OCPOLARITY_LOW
      Timer_ChX_OCFastMode: TIM_OCFAST_DISABLE
      Timer_ChX_GPIO: GPIOB
      Timer_ChX_Pin: GPIO_PIN_9
      Timer_ChX_GPIO_Alternate: GPIO_AF1_TIM17
      DMA_Config:
        Timer_Ch_DMA_Instance: DMA2_Stream0
        Timer_Ch_DMA_Request: DMA_REQUEST_TIM17_CH1
        Timer_Ch_DMA_Direction: DMA_MEMORY_TO_PERIPH
        Timer_Ch_DMA_PeriphInc: DMA_PINC_DISABLE
        Timer_Ch_DMA_MemInc: DMA_MINC_ENABLE
        Timer_Ch_DMA_PeriphDataAlignment: DMA_PDATAALIGN_HALFWORD
        Timer_Ch_DMA_MemDataAlignment: DMA_MDATAALIGN_HALFWORD
        Timer_Ch_DMA_Mode: DMA_NORMAL
        Timer_Ch_DMA_Priority: DMA_PRIORITY_MEDIUM
        Timer_Ch_DMA_FIFOMode: DMA_FIFOMODE_DISABLE
        Timer_Ch_DMA_Handle_index: TIM_DMA_ID_CC1
Tim17_Head_Config:
  Timer_Instance: &111 TIM17
  Timer_En: &112 true
  Timer_Index: 1
  Prescaler: 0
  CounterMode: TIM_COUNTERMODE_UP
  Period: 311
Tim_Ch1_Config:
  Timer_ChX: 1
  Timer_ChX_OutMode: DMA
  Timer_ChX_OCMode: &113 TIM_OCMODE_PWM2
  Timer_ChX_Pulse: &114 0
  Timer_ChX_OCPolarity: &115 TIM_OCPOLARITY_LOW
  Timer_ChX_OCFastMode: &116 TIM_OCFAST_DISABLE
  Timer_ChX_GPIO: &117 GPIOB
  Timer_ChX_Pin: &118 GPIO_PIN_9
  Timer_ChX_GPIO_Alternate: &119 GPIO_AF1_TIM17
Tim_Ch_DMA1_Config:
  Timer_Ch_DMA_Instance: DMA2_Stream0
  Timer_Ch_DMA_Request: &120 DMA_REQUEST_TIM17_CH1
  Timer_Ch_DMA_Direction: &121 DMA_MEMORY_TO_PERIPH
  Timer_Ch_DMA_PeriphInc: &122 DMA_PINC_DISABLE
  Timer_Ch_DMA_MemInc: &123 DMA_MINC_ENABLE
  Timer_Ch_DMA_PeriphDataAlignment: &124 DMA_PDATAALIGN_HALFWORD
  Timer_Ch_DMA_MemDataAlignment: &125 DMA_MDATAALIGN_HALFWORD
  Timer_Ch_DMA_Mode: &126 DMA_NORMAL
  Timer_Ch_DMA_Priority: &127 DMA_PRIORITY_MEDIUM
  Timer_Ch_DMA_FIFOMode: &128 DMA_FIFOMODE_DISABLE
  Timer_Ch_DMA_Handle_index: &129 TIM_DMA_ID_CC1
Base_Node:
  - Name: Main_Switch_Board
    Range_Name: Motor
    DeviceType: Switch_Board
    Id: 101
    CH: Head_Flag_CH0
    IO_Mod: Main_CMD_IO_Mod_ETH_To_CAN
    PC_IP: *1
    IP: 192.168.3.101
    Port: 15100
    Up_Data_Speed: 10000
    Heart_Beat: true
    DeviceConfig:
      PrintMcuTaskStack: false
      Save_to_Flash: false
      Can_S:
        - Can_Instance: 1
          Can_EN: *10
          Can_FrameFormat: *11
          Can_Mode: *12
          Can_AutoRetransmission: *13
          Can_TransmitPause: *14
          Can_ProtocolException: *15
          Can_Nominal_Prescaler: *16
          Can_Nominal_SyncJumpWidth: *17
          Can_Nominal_TimeSeg1: *18
          Can_Nominal_TimeSeg2: *19
          Can_Data_Prescaler: *20
          Can_Data_SyncJumpWidth: *21
          Can_Data_TimeSeg1: *22
          Can_Data_TimeSeg2: *23
          Can_StdFiltersNbr: *24
          Can_ExtFiltersNbr: *25
          Can_RxFifo0ElmtsNbr: *26
          Can_RxFifo0ElmtSize: *27
          Can_RxFifo1ElmtsNbr: *28
          Can_RxFifo1ElmtSize: *29
          Can_RxBuffersNbr: *30
          Can_RxBufferSize: *31
          Can_TxEventsNbr: *32
          Can_TxBuffersNbr: *33
          Can_TxFifoQueueElmtsNbr: *34
          Can_TxFifoQueueMode: *35
          Can_TxElmtSize: *36
          Can_Set_Complete: *37
        - Can_Instance: 2
          Can_EN: *10
          Can_FrameFormat: *11
          Can_Mode: *12
          Can_AutoRetransmission: *13
          Can_TransmitPause: *14
          Can_ProtocolException: *15
          Can_Nominal_Prescaler: *16
          Can_Nominal_SyncJumpWidth: *17
          Can_Nominal_TimeSeg1: *18
          Can_Nominal_TimeSeg2: *19
          Can_Data_Prescaler: *20
          Can_Data_SyncJumpWidth: *21
          Can_Data_TimeSeg1: *22
          Can_Data_TimeSeg2: *23
          Can_StdFiltersNbr: *24
          Can_ExtFiltersNbr: *25
          Can_RxFifo0ElmtsNbr: *26
          Can_RxFifo0ElmtSize: *27
          Can_RxFifo1ElmtsNbr: *28
          Can_RxFifo1ElmtSize: *29
          Can_RxBuffersNbr: *30
          Can_RxBufferSize: *31
          Can_TxEventsNbr: *32
          Can_TxBuffersNbr: *33
          Can_TxFifoQueueElmtsNbr: *34
          Can_TxFifoQueueMode: *35
          Can_TxElmtSize: *36
          Can_Set_Complete: *37
      Timer_S:
        - Timer_Index: 1
          Prescaler: 0
          CounterMode: TIM_COUNTERMODE_UP
          Period: 311
          Tim_CHX:
            Timer_ChX: 1
            Timer_ChX_OutMode: DMA
            DMA_Config:
              Timer_Ch_DMA_Instance: DMA2_Stream0
              Timer_Ch_DMA_Request: *120
              Timer_Ch_DMA_Direction: *121
              Timer_Ch_DMA_PeriphInc: *122
              Timer_Ch_DMA_MemInc: *123
              Timer_Ch_DMA_PeriphDataAlignment: *124
              Timer_Ch_DMA_MemDataAlignment: *125
              Timer_Ch_DMA_Mode: *126
              Timer_Ch_DMA_Priority: *127
              Timer_Ch_DMA_FIFOMode: *128
              Timer_Ch_DMA_Handle_index: *129
            Timer_ChX_OCMode: *113
            Timer_ChX_Pulse: *114
            Timer_ChX_OCPolarity: *115
            Timer_ChX_OCFastMode: *116
            Timer_ChX_GPIO: *117
            Timer_ChX_Pin: *118
            Timer_ChX_GPIO_Alternate: *119
          Timer_Instance: *111
          Timer_En: *112
    child:
      - *80
      - *109
      - *81
      - *82
      - *83
      - *84
      - *85
      - *86
      - *87
      - *88
      - *89
      - *90
      - *91
      - *92
      - *93
      - *94
      - *110
      - *95
      - *96
      - *97
      - *98
      - *99
      - *100
      - *101
      - *102
      - *103
      - *104
      - *105
      - *106
      - *107
      - *108